# Generated by Django 5.2.14 on 2026-05-28 07:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='업체명')),
                ('business_no', models.CharField(blank=True, max_length=20, unique=True, verbose_name='사업자등록번호')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='연락처')),
                ('source', models.CharField(choices=[('narajangteo', '나라장터'), ('manual', '수동 입력')], default='narajangteo', max_length=20, verbose_name='데이터 출처')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '공급사',
                'verbose_name_plural': '공급사 목록',
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='자재명')),
                ('ks_code', models.CharField(max_length=50, verbose_name='KS 규격 번호')),
                ('ks_grade', models.CharField(blank=True, max_length=50, verbose_name='KS 등급')),
                ('diameter', models.CharField(blank=True, max_length=20, verbose_name='규격(직경)')),
                ('category', models.CharField(choices=[('structural', '구조재'), ('non_structural', '비구조재')], default='structural', max_length=20, verbose_name='시공 분류')),
                ('is_seismic', models.BooleanField(default=False, verbose_name='내진 구조 적용 가능')),
                ('is_weldable', models.BooleanField(default=False, verbose_name='용접 시공 가능')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '자재',
                'verbose_name_plural': '자재 목록',
                'db_table': 'materials',
                'unique_together': {('ks_code', 'ks_grade', 'diameter')},
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='현장명')),
                ('site_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='현장 위도')),
                ('site_lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='현장 경도')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='필요 수량 (kg)')),
                ('deadline', models.DateField(verbose_name='납기 기한')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='core.material', verbose_name='필요 자재')),
            ],
            options={
                'verbose_name': '수요 등록',
                'db_table': 'demands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_strength_min', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='항복강도 최솟값 (MPa)')),
                ('yield_strength_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='항복강도 최댓값 (MPa)')),
                ('tensile_strength_min', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='인장강도 최솟값 (MPa)')),
                ('elongation_min', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='연신율 최솟값 (%)')),
                ('carbon_equivalent_max', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='탄소당량 최댓값')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='출처 규격 문서')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='core.material', verbose_name='자재')),
            ],
            options={
                'verbose_name': '물성치',
                'db_table': 'material_specs',
            },
        ),
        migrations.CreateModel(
            name='RegulationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astm_code', models.CharField(blank=True, max_length=50, verbose_name='동등 ASTM 규격')),
                ('jis_code', models.CharField(blank=True, max_length=50, verbose_name='동등 JIS 규격')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='감리 승인 필요')),
                ('approval_reason', models.TextField(blank=True, verbose_name='승인 필요 사유')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regulation', to='core.material', verbose_name='자재')),
            ],
            options={
                'verbose_name': '국제 규격 매핑',
                'db_table': 'regulation_mappings',
            },
        ),
        migrations.CreateModel(
            name='SupplyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField(verbose_name='계약 체결일')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='단가 (원)')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='나라장터 원본 응답')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_histories', to='core.material', verbose_name='자재')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_histories', to='core.supplier', verbose_name='공급사')),
            ],
            options={
                'verbose_name': '납품 이력',
                'verbose_name_plural': '납품 이력 목록',
                'db_table': 'supply_history',
                'ordering': ['-contract_date'],
            },
        ),
    ]
