# Generated by Django 5.2.14 on 2026-06-11 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to=settings.AUTH_USER_MODEL, verbose_name='요청자 계정'),
        ),
        migrations.CreateModel(
            name='SupplierMaterialRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='공급사명')),
                ('contact', models.CharField(blank=True, max_length=30, verbose_name='연락처')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('zip_no', models.CharField(blank=True, max_length=10, verbose_name='우편번호')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도')),
                ('main_materials', models.CharField(blank=True, max_length=200, verbose_name='주요 취급 자재')),
                ('material_name', models.CharField(max_length=100, verbose_name='자재명')),
                ('standard', models.CharField(blank=True, max_length=100, verbose_name='KS 규격')),
                ('strength_grade', models.CharField(blank=True, max_length=50, verbose_name='강도 등급')),
                ('recent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='최근 단가')),
                ('service_area', models.CharField(blank=True, max_length=200, verbose_name='납품 가능 지역')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='거리')),
                ('delivery_count', models.PositiveIntegerField(default=0, verbose_name='과거 납품 횟수')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_material_registrations', to=settings.AUTH_USER_MODEL, verbose_name='등록 공급사 계정')),
            ],
            options={
                'verbose_name': '공급사 직접 등록 자재',
                'verbose_name_plural': '공급사 직접 등록 자재 목록',
                'db_table': 'supplier_material_registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
