# Generated by Django 5.2.14 on 2026-06-22 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_material_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='KSStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='표준 번호')),
                ('revision', models.CharField(max_length=10, verbose_name='개정 연도')),
                ('title', models.CharField(max_length=200, verbose_name='표준명')),
                ('material_group', models.CharField(choices=[('rebar', '철근'), ('shape_steel', '형강·강재'), ('cement', '시멘트'), ('insulation', '단열재'), ('electrical_conduit', '전기 배관재')], db_index=True, max_length=30, verbose_name='자재 대분류')),
                ('material_subtype', models.CharField(blank=True, choices=[('deformed_rebar', '이형철근'), ('round_rebar', '원형철근'), ('h_beam', 'H형강'), ('angle', 'ㄱ형강'), ('channel', 'ㄷ형강'), ('square_tube', '각형강관'), ('steel_plate', '강판'), ('ordinary_portland', '보통 포틀랜드 시멘트'), ('blast_furnace_slag', '고로슬래그 시멘트'), ('high_early_strength', '조강 포틀랜드 시멘트'), ('eps', 'EPS'), ('xps', 'XPS'), ('glass_wool', '글라스울'), ('rigid_polyurethane', '경질 우레탄폼'), ('rigid_conduit', '경질 전선관'), ('flexible_conduit', '가요 전선관'), ('cd_conduit', 'CD관'), ('pf_conduit', 'PF관'), ('other', '기타/검토 필요')], db_index=True, max_length=30, verbose_name='세부 품목')),
                ('scope_note', models.TextField(blank=True, verbose_name='적용 범위 요약')),
                ('verification_status', models.CharField(choices=[('verified', '구조화 완료'), ('partial', '일부 구조화'), ('needs_source', '기준 자료 보강 필요')], default='partial', max_length=20, verbose_name='구조화 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KS 표준',
                'verbose_name_plural': 'KS 표준 목록',
                'db_table': 'ks_standards',
                'ordering': ['code', '-revision'],
                'constraints': [models.UniqueConstraint(fields=('code', 'revision'), name='unique_ks_standard_revision')],
            },
        ),
        migrations.CreateModel(
            name='KSSectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(db_index=True, max_length=30, verbose_name='단면 종류')),
                ('designation', models.CharField(max_length=80, verbose_name='호칭 치수')),
                ('dimensions', models.JSONField(blank=True, default=dict, verbose_name='치수')),
                ('unit_mass_kg_m', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='단위 무게 (kg/m)')),
                ('area_cm2', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='단면적 (cm²)')),
                ('section_properties', models.JSONField(blank=True, default=dict, verbose_name='단면 성능')),
                ('source_location', models.CharField(blank=True, max_length=100, verbose_name='표·부표 위치')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_profiles', to='core.ksstandard', verbose_name='표준')),
            ],
            options={
                'verbose_name': 'KS 단면 규격',
                'verbose_name_plural': 'KS 단면 규격 목록',
                'db_table': 'ks_section_profiles',
                'ordering': ['profile_type', 'designation'],
                'constraints': [models.UniqueConstraint(fields=('standard', 'profile_type', 'designation'), name='unique_ks_section_profile')],
            },
        ),
        migrations.CreateModel(
            name='KSRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_subtype', models.CharField(blank=True, choices=[('deformed_rebar', '이형철근'), ('round_rebar', '원형철근'), ('h_beam', 'H형강'), ('angle', 'ㄱ형강'), ('channel', 'ㄷ형강'), ('square_tube', '각형강관'), ('steel_plate', '강판'), ('ordinary_portland', '보통 포틀랜드 시멘트'), ('blast_furnace_slag', '고로슬래그 시멘트'), ('high_early_strength', '조강 포틀랜드 시멘트'), ('eps', 'EPS'), ('xps', 'XPS'), ('glass_wool', '글라스울'), ('rigid_polyurethane', '경질 우레탄폼'), ('rigid_conduit', '경질 전선관'), ('flexible_conduit', '가요 전선관'), ('cd_conduit', 'CD관'), ('pf_conduit', 'PF관'), ('other', '기타/검토 필요')], db_index=True, max_length=30, verbose_name='세부 품목')),
                ('grade', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='등급 또는 종류')),
                ('property_code', models.CharField(db_index=True, max_length=50, verbose_name='물성 코드')),
                ('property_name', models.CharField(max_length=100, verbose_name='검증 항목')),
                ('value_type', models.CharField(choices=[('minimum', '최솟값'), ('maximum', '최댓값'), ('range', '범위'), ('exact', '일치값'), ('classification', '분류 기준')], max_length=20, verbose_name='기준 유형')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='최솟값')),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='최댓값')),
                ('text_value', models.CharField(blank=True, max_length=200, verbose_name='분류 또는 표시값')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='단위')),
                ('condition', models.JSONField(blank=True, default=dict, verbose_name='적용 조건')),
                ('source_location', models.CharField(blank=True, max_length=100, verbose_name='표·절 위치')),
                ('display_priority', models.PositiveSmallIntegerField(default=100, verbose_name='표시 우선순위')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.ksstandard', verbose_name='표준')),
            ],
            options={
                'verbose_name': 'KS 검증 기준',
                'verbose_name_plural': 'KS 검증 기준 목록',
                'db_table': 'ks_requirements',
                'ordering': ['standard', 'display_priority', 'grade', 'property_code'],
                'indexes': [models.Index(fields=['material_subtype', 'grade'], name='ks_req_subtype_grade_idx')],
            },
        ),
    ]
