# Generated by Django 5.2.14 on 2026-06-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_community_mvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='anonymous_alias',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='display_mode',
            field=models.CharField(choices=[('profile', '실명/프로필'), ('anonymous', '익명')], default='profile', max_length=20),
        ),
    ]
