# Generated by Django 5.2.14 on 2026-06-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stagger_community_demo_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermaterialregistration',
            name='ks_standard',
            field=models.CharField(blank=True, max_length=150, verbose_name='KS 기준/등급'),
        ),
        migrations.AddField(
            model_name='suppliermaterialregistration',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, verbose_name='제조사'),
        ),
        migrations.AddField(
            model_name='suppliermaterialregistration',
            name='material_group',
            field=models.CharField(blank=True, max_length=100, verbose_name='자재군'),
        ),
        migrations.AddField(
            model_name='suppliermaterialregistration',
            name='specification',
            field=models.CharField(blank=True, max_length=150, verbose_name='규격'),
        ),
        migrations.AddField(
            model_name='suppliermaterialregistration',
            name='stock_available',
            field=models.BooleanField(default=True, verbose_name='재고 여부'),
        ),
        migrations.AddField(
            model_name='suppliermaterialregistration',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='단위'),
        ),
    ]
