# Generated by Django 5.2.14 on 2026-06-24 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_suppliermaterialregistration_ks_standard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200, verbose_name='자재명')),
                ('standard', models.CharField(blank=True, max_length=200, verbose_name='규격')),
                ('quantity', models.CharField(blank=True, max_length=100, verbose_name='문의 수량')),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='희망 납기일')),
                ('site_address', models.TextField(blank=True, verbose_name='현장 주소')),
                ('requester_name', models.CharField(blank=True, max_length=100, verbose_name='담당자명')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='연락처')),
                ('message', models.TextField(blank=True, verbose_name='요청 메모')),
                ('status', models.CharField(choices=[('pending', '협의 필요'), ('reviewing', '검토 중'), ('accepted', '납품 가능'), ('rejected', '거절')], db_index=True, default='pending', max_length=20, verbose_name='문의 상태')),
                ('status_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='상태 변경 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='요청자 계정')),
                ('supplier_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='공급사 계정')),
            ],
            options={
                'verbose_name': '공급사 문의',
                'verbose_name_plural': '공급사 문의 목록',
                'db_table': 'supplier_inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
