# Generated by Django 5.2.14 on 2026-06-24 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_supplierinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_category', models.CharField(choices=[('rebar', '철근'), ('shape_steel', '형강·강재'), ('cement', '시멘트'), ('insulation', '단열재'), ('electrical_conduit', '전기 배관재')], db_index=True, max_length=30, verbose_name='자재군')),
                ('contract_date', models.DateField(verbose_name='계약 체결일')),
                ('contract_name', models.CharField(max_length=255, verbose_name='계약명')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='계약 금액 (원)')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량')),
                ('keyword', models.CharField(blank=True, max_length=100, verbose_name='수집 검색어')),
                ('mapping_status', models.CharField(choices=[('category_only', '자재군만 확인'), ('pending_review', '검토 대기')], db_index=True, default='category_only', max_length=30, verbose_name='매핑 상태')),
                ('mapping_reason', models.CharField(blank=True, max_length=255, verbose_name='매핑 보류 사유')),
                ('source_api', models.CharField(default='나라장터', max_length=50, verbose_name='원천 API')),
                ('external_id', models.CharField(max_length=100, verbose_name='외부 계약 식별자')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='원본 응답')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_contract_histories', to='core.supplier', verbose_name='공급사')),
            ],
            options={
                'verbose_name': '자재군 계약 이력',
                'verbose_name_plural': '자재군 계약 이력 목록',
                'db_table': 'category_contract_history',
                'ordering': ['-contract_date', '-created_at'],
                'indexes': [models.Index(fields=['supplier', 'material_category', 'mapping_status'], name='category_contract_exp_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'source_api', 'external_id'), name='uniq_category_contract_source_external')],
            },
        ),
    ]
